# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://mysys.top
date_format: "ordinal"
title: MYSYS技术博客
subtitle: "研究智能化的软件"
description: "老郭的技术博客"
keywords: 郭二爷博客,郭二爷的技术博客,我的系统,老郭软件,老郭技术
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/#
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 老郭
organization: 无穷大软件
organization_url: https://www.wqdsoft.com
location: 深圳
email: guoxinzz@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基
  -
    href: /book/
    label: 书籍
  -
    href: /guide/
    label: 手册
  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
gems:
    - pygments
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
markdown: kramdown
kramdown:
    input: GFM
highlighter: pygments
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
        
    book:
        output: true
        permalink: /book/:path/

    guide:
        output: true
        permalink: /guide/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: mysys
douban_username: freedim
facebook_username: mysys
weibo_username: mysys
zhihu_username: mysys
twitter_username: mysys

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: mysys
disqus_username: mysys
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669431-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
