# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.mysys.top
date_format: "ordinal"
title: MYSYS顶级技术研究
subtitle: "研究大数据，人工智能，生命科学。"
description: "软件开中遇到的问题与解决方案记录。"
keywords: 大数据,人工智能,生命科学,大脑研究，脑电研究,机器学习
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://www.github.com/mysystop
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 老郭
organization: 无穷大软件
organization_url: https://www.wqdsoft.com
location: 广东,深圳,南山区
email: guoxinzz@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基
  -
    href: /book/
    label: 书籍
  -
    href: /guide/
    label: 手册
  -
    href: /download/
    label: 下载
  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
gems:
    - pygments
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
        
    book:
        output: true
        permalink: /book/:path/

    guide:
        output: true
        permalink: /guide/:path/
    download:
        output: true
        permalink: /download/:path/        

# ---------------- #
#      Socials     #
# ---------------- #
github_username: mysys
douban_username: freedim
facebook_username: mysys
weibo_username: mysys
zhihu_username: mysys
twitter_username: mysys

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: mysys
disqus_username: mysys
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669431-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [PHP,Golang,Java,Cscharp, C++, Python, Design Patterns]
skill_mobile_app_keywords: [React-Native,HTML5,MySQL,IOS,Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
